base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "studentLife_discipline"

urlpatterns = [
    #path('', views.caseProfile, name="case-profile"),
    path('newcase', views.NewCase, name="NewCase"),
    path('CaseList/', views.caseList, name="case-list"),
    #path('case-list/', views.caseList, name="case-list"),

    #COMMUNITY SERVICE
    path('community-service-tracker/<int:student_id>/', views.serviceTracker, name="community-service-tracker"),

    #GOOD MORAL URL
    path('RequestGoodMoral/', views.req_goodmoral, name="req_goodmoral"),
    path('goodmoral/<str:student_id>/', views.goodmoral_detail, name='goodmoral_detail'),
    path('GoodMoralTemplate/<str:student_id>/',views.GoodMoralTemplate, name="GoodMoralTemplate"),

    path('Transaction/', views.transaction, name='transaction'),
    path('approve/<int:pk>/', views.approve_request, name='approve_request'),
    path('decline/<int:pk>/', views.decline_request, name='decline_request'),

    #CRUD
    path('update-case/<str:pk>/', views.updateCase, name='update-case'),
    path('delete-case/<str:pk>/', views.deletecaserecord, name='deletecaserecord'),
    
    
    #modal part
    path('SavedSuccesfully/', views.savedcaseprofile, name="savedcaseprofile"),
     path('DeleteCaseRecord/<str:pk>/', views.deletecaserecord, name='deletecaserecord'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_user/urls.py
from django.urls import path
from . import views

app_name = 'custom_user'

urlpatterns = [
    path('index/', views.index, name='index'),  # Changed 'login/' to '' for the index page
    path('register/', views.register, name='register'),
    path('login_user/', views.login_user, name='login'),  # Changed 'login/' to 'login_user/'
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('login_admin/', views.login_admin, name='login_admin'),
    path('logout/', views.logout_user, name='logout'),
]

jobplacement/urls.py
from django.urls import path
from .views import search_suggestions, company_suggestions
from . import views
from django.conf import settings
from django.conf.urls.static import static
from custom_user.views import index as cu_index
app_name='jobplacement'

urlpatterns = [
    path('jobplacement/', views.mainpage, name="home"),
    # OJT HIRING THINGS
    path('jobplacement/ojthiring/admin', views.ojt_hiring, name="ojt_hiring"),
    path('jobplacement/ojthiring/admin/assign', views.ojt_assign_student, name='ojthiring_assign'),
    path('jobplacement/ojthiring/more/<str:id>', views.ojt_hiring_info, name='ojthiring_info'),
    path('jobplacement/ojt/requirements/tracker/', views.ojtRequirements_tracker, name="ojt_requirements_tracker"),
    path('jobplacement/ojt/requirements/tracker/update', views.ojt_requirements_accept, name='ojt_requirement_update'),
    path('jobplacement/ojthiring/clear', views.del_ojt, name="del_ojt"),
    path('jobplacement/ojt_requirements/download', views.download_zipped_ojt_templates, name="ojt_requiremets_download"),
    path('jobplacement/ojt/requirements/submit', views.ojt_requirements_submit, name='ojt_requirements_submit'),
    path('jobplacement/ojthiring/delete/<int:id>', views.ojthiring_delete, name="ojt_hiring_delete"),
   
    #   Career Guidance THINGS
    path('jobeplacement/main/', views.seminar, name="seminar_page"),
    # path('jobplacement/new_seminar/', views.newSeminar, name="new_seminar"), # create new seminar
    path('jobplacement/seminar/attendance/manager/<int:id>', views.manage_attendance, name='manage_att'), # manage students with attendance
    path('jobplacement/pending_student_att', views.pend_attendance, name='pending_attendance'), # set attendance to pending
    path('jobplacement/attendance/cancel/<str:id>', views.cancel_pending, name="cancel_pending"), # cancel pending
    path('jobplacement/seminar/attendance/manager/jobplacement/attendance/attend_all/<str:id>', views.attend_all_pending),
    path('jobplacement/attendance/attend_all/<str:id>', views.attend_all_pending, name='attend_all_pending'),
    path('jobplacement/seminar/delete/<int:id>', views.seminar_delete, name='seminar_delete'),

    # Suggestions
    path('suggestions/', search_suggestions.as_view(), name='search_suggestions'),
    path('suggestions/companies', company_suggestions.as_view(), name='company_suggestions'),

    # Transaction Report
    path('jobplacement/report/', views.transRep, name="job_trans_rep"), # report page
    # path('jobplacement/report/creation', views.transaction_creation, name="new_transaction"),
    path('jobplacement/report/print', views.transRep_print, name="rep_print"), # print report

    # Non Academic Issuance
    path('jobplacement/non_acad', views.non_acad_page, name="non_acad"),
    
    # DELETABLE PATHS
    path('jobplacement/login/', cu_index, name="student_login"),
    # path('jobplacement/signup/', views.student_signup_view, name="student_signup"),
    path('jobplacement/login/admin/', views.admin_login, name="admin_login"),
    path('jobplacement/signup/admin', views.admin_signup_view, name="admin_signup"),
    path('jobplacement/logout', views.logout_user, name="logout_user"),

    # ---------------------- STUDENTS PATHS ----------------------------------
    # homescreen sa login og admin    
    path('jobplacement/homepage/admin_student', views.admin_student, name='admin_student'),

    path('jobplacement/ojt/requirements/tracker/view/iframe/<int:id>', views.view_pdf, name='view_pdf'),
    path('jobplacement/upload/', views.file_scrapper, name='scrapper'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicalv2/urls.py
from django.urls import path
from . import views

app_name = 'medical'

urlpatterns = [
    path('patientbasicinfo/<int:student_id>/', views.patient_basic_info, name='patient_basicinfo'),
    path('medicalclearance/<int:student_id>/', views.medicalclearance_view, name='medicalclearance'),
    path('eligibilityform/<int:student_id>/', views.eligibilty_form, name='eligibility_form'),
    path('medicalcertificate/<int:student_id>/', views.med_cert, name='med_cert_for_intrams'),
    path('viewrequest/', views.view_request, name='viewrequest'),
    path('student/request/', views.submit_request, name="request"),
    path('patient/profile/', views.patient_profile, name='patient_profile'),
    path('physicalexam/<int:student_id>/', views.physical_examination, name='physical_exam'),
    path('medicalrequirementstracker/', views.student_medical_requirements_tracker, name='medtracker'),
    path('uploadrequirements/', views.upload_requirements, name='upload_requirements'),
    path('dentalservices/', views.dental_services, name='dentalservice'),
    path('dentalrequest/', views.dental_request, name='dentalrequest'),
    path('dentalschedule/', views.dental_schedule, name='dentalschedule'),
    path('listofpwd/', views.pwd_list, name='pwdlist'),
    path('pwd/<int:student_id>/', views.pwd_detail, name='pwd_detail'),
    path('prescriptions/', views.prescription, name='prescription'),
    path('prescriptionrecords/', views.view_prescription_records, name='prescription_records'),
    path('getstudentname/', views.get_student_name, name='get_student_name'),
    path('emergencyassistance/', views.emergency_asst, name='emergency_asst'),
    path('emergencyassistancerecords', views.view_emergency_health_records, name='emergency_health_records'),
    path('insuranceeligibility/', views.check_insurance_availability, name='insurance_eligibility'),
    # URL for the main transactions view
    path('transactions/', views.transactions_view, name='transactions'),
    path('monthly_transactions/', views.monthly_transactions_view, name='monthly_transactions'),
    path('daily_transactions/', views.daily_transactions_view, name='daily_transactions'),
    # path('yearly/', views.yearly_transactions, name='yearly_transactions'),
    # path('upload/', views.upload_file, name='upload'),
]

studentLife/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('custom_user.urls', 'custom_user'), namespace='custom_user')),
    path('', include(('studentLife_system.urls', 'studentLife_system'), namespace='studentLife_system')),
    path('', include('jobplacement.urls')),
    path('medical/', include(('medicalv2.urls'), namespace='medicalv2')),
    path('discipline/', include(('base.urls'), namespace='studentLife_discipline')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/studentorg/ADMIN/admin_login.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Admin Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/org.css' %}">
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <link rel="stylesheet" href="{% static '/css/logins.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>

    <div class="logincontainer">
        <div class="maincontain">
            <div class="subcontain" style="display:block; height:10%; overflow: hidden;" >
                <div class="f1">
                <img src="{% static '/css/CTU_logo.png' %}" class="logoimg">
                <h1 >
                    Admin Login</h1>
                </div>
                {% if messages %}
                <ul class="stop hd">
                    {% for message in messages %}
                    <li style="color:black;">{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <form method="post" style="margin-top:10px;">
                    {% csrf_token %}
                    <div class="form-group stop">
                        <label for="id_admin_username">Username:</label>
                        {{ form.admin_username }}
                    </div>
                    <div class="form-group">
                        <label for="id_admin_password">Password:</label>
                        {{ form.admin_password }}
                    </div>
                    <button type="submit" class="button" style="width: 100%;">Login</button>
                    <a href="{% url 'studentLife_system:logins' %}" class="button" style="width: 100%; margin:0px; margin-top:10px; text-align: center;">Go Back</a>
                </form>
            </div>
        </div>
    </div>
</body>

</html>

templates/studentorg/ADMIN/admin_manageadviser.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Student Organization (Admin)</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/org.css' %}">
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <link rel="stylesheet" href="{% static '/css/tables.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body>

    <div class="nav-container">
        <div class="orange-bar">
            <img src="{% static '/css/CTU_logo.png' %}" class="logo">
            <img src="{% static '/css/barSort.png' %}" class="bars">
        </div>

        <nav class="side-nav">
            <ul>
                 <li><a href="#" class="studentlife-btn">OFFICE OF STUDENT LIFE 
                <span class="fas fa-caret-down first"></span>
            </a>
                <ul class="studentlife">
                    <li><a href="/equipmenttrackerAdmin">Equipment Tracker(Admin)</a></li>
                    <li><a href="/requested-gmc">Good Moral Certificate Issuance(Admin)</a></li>
                    <li><a href="/upload">PPMP Tracker(Admin)</a></li>
                    <li><a href="/monthlyCalendarAdmin">Monthly Calendar of Activites(Admin)</a></li>
                    <li><a href="/transactionreport">Transaction Report(Admin)</a></li>
                </ul>
            </li>
            <li><a href="#" class="scholar-btn">SCHOLARSHIP
                <span class="fas fa-caret-down second"></span>
            </a>
            <ul class="scholar-show">
                <li><a href="#">Submission of Requirements Tracker(Admin)</a></li>
                <li><a href="#">Scholars Profile and Validation(Admin)</a></li>
                <li><a href="#">Grade Submission with GPA Computation(Admin)</a></li>
                <li><a href="#">Mentorship Program(Admin)</a></li>
                <li><a href="#">Admin Cost Liquidation Tracker(Admin)</a></li>
                <li><a href="#">CHED Reports Submission(Admin)</a></li>
                <li><a href="#">Transaction Reports(Admin)</a></li>
            </ul>
            </li>
            <li><a href="#" class="jobplace-btn">JOB PLACEMENT
                <span class="fas fa-caret-down third"></span>    
            </a>
            <ul class="jobplace-show">
                <li><a href="{% url 'jobplacement:ojt_hiring' %}">OJT Hiring</a></li>
                <li><a href="{% url 'jobplacement:seminar_page' %}">Career Guidance Tracker</a></li>
                <li><a href="{% url 'jobplacement:ojt_requirements_tracker' %}">OJT Requirements Tracker</a></li>
                {% if request.user.is_staff %}
                <li><a href="{% url 'jobplacement:non_acad' %}">Non-Academic Award Issuance</a></li>
                <li><a href="{% url 'jobplacement:job_trans_rep' %}">Transaction Reports</a></li>
                {% endif%}
                {% if request.user.is_superuser %}
                <li><a href="{% url 'jobplacement:admin_signup' %}">Admin Signup</a></li>
                {% endif %}
                {% if request.user.is_staff %}
                <li><a href="{% url 'custom_user:register' %}">Student Signup</a></li>
                {% endif %} 
            </ul>
            </li>
            <li><a href="#" class="student_disc-btn">STUDENT DISCIPLINE
               <span class="fas fa-caret-down fourth"></span>
            </a>
            <ul class="student_disc-show">
                <li><a href="{% url 'studentLife_discipline:transaction' %}">Transaction Reports</a></li>
            </ul>
            </li>
            <li><a href="#" class="guide-btn">GUIDANCE
               <span class="fas fa-caret-down fifth"></span>
            </a>
            <ul class="guide-show">
                <li><a href="{% url 'studentLife_system:Counseling App With Scheduler Admin View'%}">Counseling App with Scheduler(Admin)</a></li>
                <li><a href="{% url 'studentLife_system:Intake Interview' %}">Intake Interview(Admin)</a></li>
                <li><a href="{% url 'studentLife_system:Exit Interview Admin View'%}">Exit Interview(Admin)</a></li>
                <li><a href="{% url 'studentLife_system:OJT Assessment Admin View'%}">OJT Assessments/Psychological Issuance(Admin)</a></li>
                <li><a href="{% url 'studentLife_system:guidance_transaction' %}">Transaction Reports(Admin)</a></li>
            </ul>
            </li>
            <li><a href="#" class="alumni-btn">ALUMNI
                <span class="fas fa-caret-down sixth"></span>
             </a>
             <ul class="alumni-show">
                 <li><a href="{% url 'studentLife_system:admin_idRequest' %}">Alumni ID Requests</a></li>
                 <li><a href="{% url 'studentLife_system:admin_gradTracer' %}">Graduate Tracer</a></li>
                 <li><a href="{% url 'studentLife_system:admin_events' %}">Alumni Reunion and Events</a></li>
                 <li><a href="{% url 'studentLife_system:admin_jobfairs' %}">Job Fairs</a></li>
                 <li><a href="{% url 'studentLife_system:admin_yearbook' %}">Digital Yearbook</a></li>
                 <li><a href="{% url 'studentLife_system:transaction_alumni' %}">Transaction Reports(Admin)</a></li>
             </ul>
             </li>
             <li><a href="#" class="community-btn">COMMUNITY INVOLVEMENT
                <span class="fas fa-caret-down seventh"></span>
             </a>
             <ul class="community-show">
                 
            <li><a href="{% url 'studentLife_system:program-form' %}">Events(Admin)</a></li>
            <li><a href="{% url 'studentLife_system:project-form' %}">Crowd Funding Project(Admin)</a></li>
            <li><a href="{% url 'studentLife_system:donation-validate' %}">Donation Validates(Admin)</a></li>
            <li><a href="{% url 'studentLife_system:donation_dashboard' %}">Donations(Admin)</a></li>
            <li><a href="{% url 'studentLife_system:reports' %}">Transaction Reports(Admin)</a></li>
                 
             </ul>
             </li>
             <li><a href="#" class="student_org-btn">STUDENT ORGANIZATION
                <span class="fas fa-caret-down eight"></span>
             </a>
             <ul class="student_org-show">
                 <li><a href="{% url 'studentLife_system:logins' %}">Org Profile</a></li>
             </ul>
             </li>
            <li><a href="#" class="medical-btn">MEDICAL
               <span class="fas fa-caret-down ninth"></span>
            </a>
            <ul class="medical-show">
                <li><a href="{% url 'medicalv2:patient_profile'%}">Patient Profile(Admin)</a></li>
                <li><a href="{% url 'medicalv2:viewrequest'%}">View Requests(Admin)</a></li>
                <li><a href="{% url 'medicalv2:emergency_asst'%}">Emergency Health Assistance(Admin)</a></li>
                <li><a href="{% url 'medicalv2:pwdlist'%}">PWD Profile(Admin)</a></li>
                <li><a href="{% url 'medicalv2:dentalrequest'%}">Dental Services(Admin)</a></li>
                <li><a href="{% url 'medicalv2:prescription'%}">Prescription Issuance(Admin)</a></li>
                <li><a href="{% url 'medicalv2:transactions'%}">Transaction Reports(Admin)</a></li>
                <br><br><br>
            </ul>
            </li>
            </ul>
        </nav>
    </div>

 

    <div class="pcontainer">
        <div class="headert">
            <h1>Student Organization(Admin)</h1>
        </div>
        <p class="pages"><a href="{% url 'studentLife_system:logins' %}">Back To Logins</a> > <a href="{% url 'studentLife_system:admin_manageadviser' %}">Manage Adviser</a></p>


        <div class="tabs" style="margin-top:0px;">
            <div class="tabs">
                <a href="/admin_manageofficer" class="tab">Manage Officer</a>
                <a href="/admin_manageadviser" class="tab active">Manage Adviser</a>
                <a href="/admin_manageproject" class="tab">Manage Projects</a>
                <a href="/admin_managefinancial" class="tab">Manage Financial</a>
                <a href="/admin_manage_accreditations" class="tab">Manage Applications</a>
                <a href="/admin_transactionreport" class="tab">Manage Transactions </a>
            </div>
        </div>
        <div class="maincontain">
            <div class="subcontain">
                <table>
                    <thead>
                        <tr>
                            <th>Officer ID</th>
                            <th>Profile Picture</th>
                            <th>Last Name</th>
                            <th>First Name</th>
                            <th>Middle Name</th>
                            <th>Department</th>
                            <th>Position</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for adviser in advisers %}
                        <tr>
                            <td>{{ adviser.id }}</td>
                            <td>
                                {% if adviser.Adviser_profile_picture %}
                                    <a href="{{ adviser.Adviser_profile_picture.url }}" target="_blank">
                                        <img src="{{ adviser.Adviser_profile_picture.url }}" alt="Profile Picture" style="width: 50px; height: 50px;">
                                    </a>
                                {% endif %}
                            </td>
                            <td>{{ adviser.surname }}</td>
                            <td>{{ adviser.firstname }}</td>
                            <td>{{ adviser.middlename }}</td>
                            <td>{{adviser.department}}</td>
                            <td>{{ adviser.position }}</td>
                            <td>{{ adviser.get_status_display }}</td>
                            <td>
                                <form method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="adviser_id" value="{{ adviser.id }}">
                                    {% if adviser.status == 'pending' %}
                                    <button type="submit" style='background-color: #66bb6a;' name="action"
                                        class='button' value="approve">Approve</button>
                                    <button type="submit" style='background-color: #ef5350;' name="action"
                                        class='button' value="decline">Decline</button>
                                    {% endif %}
                                    {% if adviser.status == 'approved' %}
                                    <button type="submit" style='background-color: #ffa726;' class='button'
                                        name="action" value="terminate">Terminate</button>
                                    {% endif %}
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>

</html>

templates/studentorg/ADMIN/officer_login.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Officer Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/org.css' %}">
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <link rel="stylesheet" href="{% static '/css/logins.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body>

    <div class="logincontainer">
        <div class="maincontain">
            <div class="subcontain" style="display:block; height:10%; overflow: hidden;">
                <div class="f1">
                    <img src="{% static '/css/CTU_logo.png' %}" class="logoimg">
                    <h1>Officer Login</h1>
                </div>
                {% if messages %}

                <ul class="stop hd">
                    {% for message in messages %}
                    <li style="color:black;">{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <form method="post" style="margin-top:10px;">
                    {% csrf_token %}
                    <div class="form-group stop">
                        {{ form.username.label_tag }}
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        {{ form.password.label_tag }}
                        {{ form.password }}
                    </div>
                    <button type="submit" class="button" style="width: 100%;">Login</button>
                    <a href="{% url 'studentLife_system:logins' %}" class="button" style="width: 100%; margin:0px; margin-top:10px; text-align: center;">Go Back</a>

                </form>
            </div>
        </div>
    </div>
</body>

</html>

templates/studentorg/ADMIN/view_accreditation.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Accreditation Review</title>
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
    }
    .container {
        max-width: 800px;
        margin: 20px auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
    h1 {
        text-align: center;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }
    th {
        background-color: #f2f2f2;
    }
    .buttons {
        margin-top: 20px;
        text-align: center;
    }
    button {
        padding: 10px 20px;
        margin: 0 10px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    .approve {
        background-color: #4CAF50;
        color: #fff;
    }
    .decline {
        background-color: #f44336;
        color: #fff;
    }
</style>
</head>
<body>
{% for accreditation in accreditations %}
<div class="container">
    <h1>Accreditation Review</h1>
    <div class="">
        <strong>Organization: {{ accreditation.organization }}</strong>
    </div>

    <table>
        <tr>
            <th>Document</th>
            <th>Files</th>
        </tr>
        <tr>
            <td>Letter of Intent</td>
            <td>{% if accreditation.letter_of_intent %}<a href="{{ accreditation.letter_of_intent.url }}" target="_blank">View Letter</a>{% endif %}</td>
        </tr>
        <tr>
            <td>List of Officers</td>
            <td>{% if accreditation.list_of_officers %}<a href="{{ accreditation.list_of_officers.url }}" target="_blank">View List</a>{% endif %}</td>
        </tr>
        <tr>
            <td>Certificate of Registration</td>
            <td>{% if accreditation.certificate_of_registration %}<a href="{{ accreditation.certificate_of_registration.url }}" target="_blank">View Certificate</a>{% endif %}</td>
        </tr>
        <tr>
            <td>List of Members</td>
            <td>{% if accreditation.list_of_members %}<a href="{{ accreditation.list_of_members.url }}" target="_blank">View Members</a>{% endif %}</td>
        </tr>
        <tr>
            <td>Accomplishment Report</td>
            <td>{% if accreditation.accomplishment_report %}<a href="{{ accreditation.accomplishment_report.url }}" target="_blank">View Report</a>{% endif %}</td>
        </tr>
        <tr>
            <td>Calendar of Activities</td>
            <td>{% if accreditation.calendar_of_activities %}<a href="{{ accreditation.calendar_of_activities.url }}" target="_blank">View Activities</a>{% endif %}</td>
        </tr>
        <tr>
            <td>Financial Statement</td>
            <td>{% if accreditation.financial_statement %}<a href="{{ accreditation.financial_statement.url }}" target="_blank">View Statement</a>{% endif %}</td>
        </tr>
        <tr>
            <td>Bank Passbook</td>
            <td>{% if accreditation.bank_passbook %}<a href="{{ accreditation.bank_passbook.url }}" target="_blank">View Passbook</a>{% endif %}</td>
        </tr>
        <tr>
            <td>Inventory of Properties</td>
            <td>{% if accreditation.inventory_of_properties %}<a href="{{ accreditation.inventory_of_properties.url }}" target="_blank">View Inventory</a>{% endif %}</td>
        </tr>
        <tr>
            <td>Organization Bylaws</td>
            <td>{% if accreditation.organization_bylaws %}<a href="{{ accreditation.organization_bylaws.url }}" target="_blank">View ByLaws</a>{% endif %}</td>
        </tr>
        <tr>
            <td>Faculty Adviser Appointment</td>
            <td>{% if accreditation.faculty_adviser_appointment %}<a href="{{ accreditation.faculty_adviser_appointment.url }}" target="_blank">View Appointment</a>{% endif %}</td>
        </tr>
        <tr>
            <td>Other Documents</td>
            <td>{% if accreditation.other_documents %}<a href="{{ accreditation.other_documents.url }}" target="_blank">View Other Documents</a>{% endif %}</td>
        </tr>
    </table>
</div>
{% endfor %}
</body>
</html>