base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "studentLife_discipline"

urlpatterns = [
    #path('', views.caseProfile, name="case-profile"),
    path('newcase', views.NewCase, name="NewCase"),
    path('CaseList/', views.caseList, name="case-list"),
    #path('case-list/', views.caseList, name="case-list"),

    #COMMUNITY SERVICE
    path('community-service-tracker/<int:student_id>/', views.serviceTracker, name="community-service-tracker"),

    #GOOD MORAL URL
    path('RequestGoodMoral/', views.req_goodmoral, name="req_goodmoral"),
    path('goodmoral/<str:student_id>/', views.goodmoral_detail, name='goodmoral_detail'),
    path('GoodMoralTemplate/<str:student_id>/',views.GoodMoralTemplate, name="GoodMoralTemplate"),

    path('Transaction/', views.transaction, name='transaction'),
    path('approve/<int:pk>/', views.approve_request, name='approve_request'),
    path('decline/<int:pk>/', views.decline_request, name='decline_request'),

    #CRUD
    path('update-case/<str:pk>/', views.updateCase, name='update-case'),
    path('delete-case/<str:pk>/', views.deletecaserecord, name='deletecaserecord'),
    
    
    #modal part
    path('SavedSuccesfully/', views.savedcaseprofile, name="savedcaseprofile"),
     path('DeleteCaseRecord/<str:pk>/', views.deletecaserecord, name='deletecaserecord'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentLife/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('custom_user.urls', 'custom_user'), namespace='custom_user')),
    path('', include(('studentLife_system.urls', 'studentLife_system'), namespace='studentLife_system')),
    path('', include('jobplacement.urls')),
    path('medical/', include(('medicalv2.urls'), namespace='medicalv2')),
    path('discipline/', include(('base.urls'), namespace='studentLife_discipline')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User 
from datetime import timedelta, datetime, date
from django.utils.dateparse import parse_date
from django.db.models import Max
# Create your models here.

class Studentinfo(models.Model):
    studentID = models.IntegerField(primary_key=True)
    lrn = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    firstname = models.CharField(max_length=100)
    middlename = models.CharField(max_length=100, null=True, blank=True)
    degree = models.CharField(max_length=100)
    year_level = models.PositiveIntegerField()
    sex = models.CharField(max_length=6)
    email = models.EmailField()
    contact_number = models.CharField(max_length=15)

    
    SANCTION_CHOICES = [
        ('apology_letter', 'Apology Letter'),
        ('community_service', 'Community Service'),
        ('suspension', 'Suspension'),
        ('apology_letter_community_service', 'Apology Letter and Community Service'),
        ('expulsion', 'Expulsion'),
    ]
    
    sanction = models.CharField(max_length=50, choices=SANCTION_CHOICES, null=True, blank=True)
    sanction_completed = models.BooleanField(default=False, null=True, blank=True)
    apology_letter = models.FileField(upload_to='apology_letters/', null=True, blank=True)
    community_service_hours = models.IntegerField(null=True, blank=True)
    community_service_deadline = models.DateField(null=True, blank=True)
    suspension_start_date = models.DateField(null=True, blank=True)
    suspension_end_date = models.DateField(null=True, blank=True)
    
    def __str__(self):
        return f'{self.lastname}, {self.firstname}'
    
    def save(self, *args, **kwargs):
        if self.suspension_end_date and self.suspension_end_date < date.today():
            self.sanction_completed = True
        super().save(*args, **kwargs)

class CaseProfile(models.Model):
    student = models.ForeignKey(Studentinfo, on_delete=models.CASCADE)
    violation = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    received_by = models.CharField(max_length=100)
    reported_by = models.CharField(max_length=100)
    case_date = models.DateField()
    case_class = models.CharField(max_length=100)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.student.lastname

    def determine_sanction(self):
        highest_case_class = self.get_highest_case_class()

        if highest_case_class == '1':
            self.apply_sanction(1)
        elif highest_case_class == '2':
            self.apply_sanction(2)
        elif highest_case_class == '3':
            self.apply_sanction(3)

    def apply_sanction(self, highest_case_class):
        num_case_profiles = self.student.caseprofile_set.count()
        case_date = self.case_date
        if isinstance(case_date, str):
            case_date = parse_date(case_date)
        if isinstance(case_date, datetime):
            case_date = case_date.date()

        community_service_hours = 0
        community_service_deadline = None
        suspension_start_date = None
        suspension_end_date = None

        if highest_case_class == 1:
            if num_case_profiles == 1:
                self.student.sanction = "apology_letter"
                community_service_hours = 0
                community_service_deadline = case_date + timedelta(weeks=8)
            elif num_case_profiles == 2:
                self.student.sanction = "community_service"
                community_service_hours = 10
                community_service_deadline = case_date + timedelta(weeks=2)
            elif num_case_profiles == 3:
                self.student.sanction = "community_service"
                community_service_hours = 40
                community_service_deadline = case_date + timedelta(weeks=4)
            elif num_case_profiles == 4:
                self.student.sanction = "suspension"
                suspension_start_date = case_date
                suspension_end_date = case_date + timedelta(weeks=3)
            elif num_case_profiles == 5:
                self.student.sanction = "expulsion"
                
        elif highest_case_class == 2:
            if num_case_profiles == 1:
                self.student.sanction = "apology_letter"
                community_service_hours = 0
                community_service_deadline = case_date + timedelta(weeks=6)
            elif num_case_profiles == 2:
                self.student.sanction = "community_service"
                community_service_hours = 10
                community_service_deadline = case_date + timedelta(weeks=4)
            elif num_case_profiles == 3:
                self.student.sanction = "community_service"
                community_service_hours = 40
                suspension_start_date = case_date
                suspension_end_date = case_date + timedelta(weeks=3)
            elif num_case_profiles == 4:
                self.student.sanction = "suspension"
                suspension_start_date = case_date
                suspension_end_date = case_date + timedelta(weeks=3)
            elif num_case_profiles == 5:
                self.student.sanction = "expulsion"
               

        elif highest_case_class == 3:
            if num_case_profiles == 1:
                self.student.sanction = "apology_letter"
                community_service_hours = 10
                community_service_deadline = case_date + timedelta(weeks=4)
            elif num_case_profiles == 2:
                self.student.sanction = "community_service"
                community_service_hours = 20
                community_service_deadline = case_date + timedelta(weeks=8)
            elif num_case_profiles == 3:
                self.student.sanction = "suspension"
                suspension_start_date = case_date
                suspension_end_date = case_date + timedelta(weeks=26)  # 1 semester (approx. 6 months)
            elif num_case_profiles == 4:
                self.student.sanction = "suspension"
                suspension_start_date = case_date
                suspension_end_date = case_date + timedelta(weeks=52)  # 2 semesters (approx. 1 year)
            elif num_case_profiles == 5:
                self.student.sanction = "expulsion"

        # Apply deadlines and save
        self.student.community_service_hours = community_service_hours
        self.student.community_service_deadline = community_service_deadline
        self.student.suspension_start_date = suspension_start_date
        self.student.suspension_end_date = suspension_end_date
        self.student.save()

    def get_highest_case_class(self):
        case_classes = set(cp.case_class for cp in self.student.caseprofile_set.all())
        if '3' in case_classes:
            return '3'
        elif '2' in case_classes:
            return '2'
        elif '1' in case_classes:
            return '1'
        else:
            return None
        
class CommunityServiceTracker(models.Model):
    student = models.ForeignKey(Studentinfo, on_delete=models.CASCADE)
    service_date = models.DateField()
    time_in = models.TimeField()
    time_out = models.TimeField()
    # time_rendered = models.IntegerField()
    student_signature = models.CharField(max_length=100)
    remarks = models.CharField(max_length=100, null=True, blank=True)

    def time_rendered(self):
        delta = datetime.combine(self.service_date, self.time_out) - datetime.combine(self.service_date, self.time_in)
        total_minutes = delta.total_seconds() / 60
        hours = int(total_minutes // 60)
        minutes = int(total_minutes % 60)
        return f'{hours} hours {minutes} minutes'
    
    def total_time_rendered(self):
        delta = datetime.combine(datetime.today(), self.time_out) - datetime.combine(datetime.today(), self.time_in)
        total_minutes = delta.total_seconds() / 60
        hours = int(total_minutes // 60)
        minutes = int(total_minutes % 60)
        return hours, minutes

class GoodMoral(models.Model):
    case_profile = models.ForeignKey(CaseProfile, on_delete=models.SET_NULL, null=True)
    student = models.ForeignKey(Studentinfo, on_delete=models.SET_NULL, null=True)
    reason = models.TextField()
    is_approved = models.BooleanField(default=False)
    is_declined = models.BooleanField(default=False)
    decision_date = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.student.lastname if self.student else "No student assigned"

class TransactionReport(models.Model):
    name = models.CharField(max_length=100)
    course_year_section = models.CharField(max_length=100)
    reason = models.CharField(max_length=100)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name

base/forms.py
from django.forms import ModelForm
from . models import CaseProfile, GoodMoral

class CaseProfileForm(ModelForm):
    class Meta:
        model = CaseProfile
        fields = ['case_date','student', 'violation', 'description', 'received_by', 'reported_by']

base/templates/base/CommunityServiceTracker.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Community Service Tracker</title>
    <link rel="stylesheet" href="{% static 'studentdiscipline/css/cstracker.css' %}">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
</head>
<body>
    <div class="header-logo">
        <img src="{% static 'studentdiscipline/imgs/newlogo.jpg' %}" alt="new ctu logo">
    </div>
    
    <div class="container">
        <h2>Community Service Time Record</h2>
        <div class="btn-container">
            <a href="{% url 'studentLife_discipline:NewCase' %}" class="btn-home">Home</a>
        </div>
        
        <div class="table-container">
            <form id="serviceForm" method="post" action="">
                {% csrf_token %}
                <div class="input-container">
                    <div class="inputs">
                        <label for="name">Name:</label>
                        <input type="text" id="name" value="{{student.lastname}}, {{student.firstname}} {{student.middlename}}">
                    </div>
                    <div class="inputs">
                        <label for="year_section">Course/Year/Section:</label>
                        <input type="text" id="year_section" value="{{student.degree}} - {{student.year_level}} ">
                    </div>
                    <div class="inputs">
                        <label for="service-hours">Community service hours: </label>
                        <input type="text" id="service-hours" value="{{student.community_service_hours}}">
                    </div>
                    <div class="inputs">
                        <label for="service-deadline">Community service deadline: </label>
                        <input type="text" id="service-deadline" value="{{student.community_service_deadline}}">
                    </div>
                </div>
                <table id="serviceTable">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Time In</th>
                            <th>Time Out</th>
                            <th>Hours Rendered</th>
                            <th>Student Signature</th>
                            <th>Remark</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for service in community_services %}
                        <tr>
                            <td>{{ service.service_date }}</td>
                            <td>{{ service.time_in }}</td>
                            <td>{{ service.time_out }}</td>
                            <td>{{ service.time_rendered }}</td>
                            <td>{{ service.student_signature }}</td>
                            <td>{{ service.remarks }}</td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td><input type="date" id="id_date" name="service_date"></td>
                            <td><input type="time" id="id_time_in" name="time_in"></td>
                            <td><input type="time" id="id_time_out" name="time_out"></td>
                            <td><input type="text" id="id_hours_rendered" name="hours_rendered" readonly></td>
                            <td><input type="text" id="id_student_signature" name="student_signature"></td>
                            <td><input type="text" id="id_remark" name="remarks"></td>
                        </tr>
                    </tbody>
                </table>
                <p>Total Time Rendered: {{total_hours}} hour, {{total_minutes}} minutes</p>
                {% if student.sanction_completed is True %}
                    <p>Sanction Completed</p>
                {% else %}
                    <p>Sanction Not Completed</p>
                {% endif %}
                <button class="btn-save" type="submit">Save</button>
            </form>
        </div>
       
        
    </div>
    <script src="{% static 'js/cstracker.js' %}"></script>
</body>
</html>

base/templates/base/ToCommunityTracker.html
{% extends 'main.html' %}

{% load static %}

{% block bodycontent %}
<link rel="stylesheet" href="{% static 'studentdiscipline/css/tocomm.css' %}">
<div class="to-communityservice">
            
    <a href="{% url 'studentLife_discipline:service-view' %}" class="user-btn">User</a>
    <a href="{% url 'studentLife_discipline:case-list' %}" class="admin-btn">Admin</a>

</div>
{% endblock %}

base/templates/base/Transactionreport.html
{% extends 'main.html' %}

{% load static %}

{% block bodycontent %}
<link rel="stylesheet" href="{% static 'studentdiscipline/css/Transact.css' %}">
<script src="{% static 'studentdiscipline/js/printtransac.js' %} "></script>
<div class="transact-container">
    <img src="{% static 'studentdiscipline/imgs/newlogo.jpg' %}">
    <div class="transact-header">
        <form method="GET" class="filter-form">
            <div class="filter-but">
                <button type="submit" class="myButton" name="filter-btn">Filter</button>
            </div>
            <div class="filter-fields">
                <label for="query">Name:</label>
                <input type="text" id="query" name="query" placeholder="Enter name">
                <label class="date1" for="date_filter">Select Date:</label>
                <select id="date_filter" name="date_filter" style="color: black;">
                    <option value="" style="color: black;">-- Select --</option>
                    <option value="daily" style="color: black;">Daily</option>
                </select>
                <label class="month1" for="month_filter">Select Month:</label>
                <select id="month_filter" name="month_filter" style="color: black;">
                    <option value="" style="color: black;">-- Select --</option>
                    <option value="1" style="color: black;">January</option>
                    <option value="2" style="color: black;">February</option>
                    <option value="3" style="color: black;">March</option>
                    <option value="4" style="color: black;">April</option>
                    <option value="5" style="color: black;">May</option>
                    <option value="6" style="color: black;">June</option>
                    <option value="7" style="color: black;">July</option>
                    <option value="8" style="color: black;">August</option>
                    <option value="9" style="color: black;">September</option>
                    <option value="10" style="color: black;">October</option>
                    <option value="11" style="color: black;">November</option>
                    <option value="12" style="color: black;">December</option>
                </select>
            </div>
        </form>
    </div>

    <div class="transact-table">
        <h2>Transaction Report</h2>
        <table>
            <thead>
                <tr>
                    <th style="width: 50px;">Transaction ID</th>
                    <th style="width: 60px;">Student</th>
                    <th style="width: 90px;">Reason</th>
                    <th style="width: 80px;">Date</th>
                    <th>Request</th>
                </tr>
            </thead>
            <tbody>
                {% for goodmoral in goodmorals %}
                <tr>
                    <td>{{ goodmoral.id }}</td>
                    <td>{{ goodmoral.student.lastname }}, {{ goodmoral.student.firstname }} {{ goodmoral.student.middlename }}</td>
                    <td>{{ goodmoral.reason }}</td>
                    <td>{{ goodmoral.created}}</td>
                    <td>
                        {% if not goodmoral.is_approved and not goodmoral.is_declined %}
                            <a href="{% url 'studentLife_discipline:approve_request' goodmoral.id %}" class="btn btn-success">✔️</a>
                            <a href="{% url 'studentLife_discipline:decline_request' goodmoral.id %}" class="btn btn-danger">❌</a>
                        {% elif goodmoral.is_approved %}
                            Approved
                        {% elif goodmoral.is_declined %}
                            Declined
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="dashboard-btn">
        <button onclick="printtransac()" type="submit" class="myButton1" name="print-btn">Print</button>
    </div>
</div>
{% endblock %}

base/templates/base/good_moral_certificate.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="shortcut icon" type="x-icon" href="{% static 'studentdiscipline/images/CTU_logo.png' %}">
    <title>STUDENT LIFE INFORMATION SYSTEM</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'studentdiscipline/css/gmc.css' %}">
</head>
<body>
    <div class="btn-container">
        <a href="{{request.META.HTTP_REFERER}}" style="color: black;">
            <i style="font-size:24px" class="fa">&#xf060;</i>
        </a>
    </div>
    <div class="certificate-container">
        <div class="upper-contents">
            <div class="logo1-container">
                <img src="{% static 'studentdiscipline/imgs/CTU_logo.png'%}" alt="School Logo" class="logo1">
            </div>
            <div class="logo2-container">
                <img src="{% static 'studentdiscipline/imgs/BagongPilipinaslogo.png' %}" alt="School Logo" class="logo2">
            </div>
            <div class="content1">REPUBLIC OF THE PHILIPPINES</div>
            <div class="content2">CEBU TECHNOLOGICAL UNIVERSITY</div>
            <div class="content3">ARGAO CAMPUS</div>
            <div class="content4">Ed Kintanar Street, Lamacan, Argao, Cebu</div>
            <div class="content4">Website: https://www.argao.ctu.edu.ph E-mail: cdargao@ctu.edu.ph</div>
            <div class="content4">Phone No.:(032) 401-0737 local 1700</div>
            <div class="line"></div>
        </div>
        <div class="maincontents">
            <h4>STUDENT AFFAIRS OFFICE</h4>
            <h3>GUIDANCE SERVICES CENTER</h3>
            <h2>CERTIFICATION OF GOOD MORAL CHARACTER</h2>
        </div>
        <div class="sub-contents">
            <h3>To Whom It May Concern:</h3>
            <p>This is to certify that <span class="underline">{{ student.lastname }}, {{ student.firstname }} {{ student.middlename }}</span> is a student of Cebu Technological University-Argao Campus taking <span class="underline">{{ student.degree }}</span>.</p>
            
            {% if cases == 0 %}
            <p>During his/her stay in this institution, we have not found any record to show that he/she committed any act contrary to the rules and regulations of the school.</p>
            {% else %}
            <p>During his/her stay at this institution, we have found {{ cases }} instances of rule violations. This indicates a lack of adherence to the school's rules and regulations.</p>
            {% endif %}
            <p>This certification is issued on <span class="underline">
                {% for gm in goodmoral %}
                {{ gm.created|date:"F j, Y" }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </span> for any legal purpose of his/her <span class="underline">
                {% for gm in goodmoral %}
                    {{ gm.reason }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </span>.</p> 
            <div class="Dean">
                <p>RHEA JANE L. CAYNILA, RPm, RGC</p>
                <p id="campus-director">Guidance Services Coordinator</p>
                <p id="lower-content">MELANIE R. ALBARRACIN</p>
                <p id="campus-director">Director, Student Life</p>
            </div>
        </div>
        <div class="ornum">
            <p>PAID OR #{{ or_num }}</p>
            <p>Not Valid Without School Seal</p>
            <p>Or with Erasure or Alteration</p>
        </div>    
        <div class="bottomline"></div>
        <img class="footerImg" src="{% static 'studentdiscipline/imgs/footer.png' %}">
    </div>
    <div class="print">
        <button id="print"><i class="fa-solid fa-print"></i></button>
    </div>
    <script src="{% static 'studentdiscipline/js/gm.js'%}"></script>
</body>
</html>

base/templates/base/goodmoralTable.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Case List</title>
    <link rel="stylesheet" href="{% static 'studentdiscipline/css/gmTable.css' %}">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'studentdiscipline/imgs/CTU_logo.png' %}" type="image/png">
</head>
<body>
    <div class="header-logo">
        <img src="{% static 'studentdiscipline/imgs/newlogo.jpg' %}" alt="new ctu logo">
    </div>
    
    
    <div class="container">
        <h2>Request Good Moral</h2>
        <div class="btn-container">
            <a href="{{request.META.HTTP_REFERER}}" style="color: black;">
                <i style="font-size:24px" class="fa">&#xf060;</i>
            </a>
        </div>

        <p>Full Name: {{ student.lastname }}, {{ student.firstname }} {{ student.middlename }}</p>
        <p>Year Level: {{ student.year_level }}</p>
        
        {% if not existing_request %}
        <form action="" method="POST">
            {% csrf_token %}
            <p>Sanction: {{ student.sanction }}</p>
            {% if student.sanction_completed == True or case_count == 0 %}
            <label for="reason">Reason:</label>
            <input class="reason-txt" type="text" name="student_reason">
            <p>Number of cases: {{ case_count }}</p>
            <p>Sanction Completed</p>
            <div class="req-btn">
                <input class="request-btn" type="submit" value="Submit" />
            </div>
            {% endif %}
        </form>
            {% if case_count != 0 and student.sanction_completed == False%}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Sanction On Progress</p>
                    {% if student.sanction == 'apology_letter' %}
                        <label for="apology_letter">Upload Apology Letter:</label>
                        <input type="file" name="apology_letter">
                        <br>
                        <br>
                        <button type="submit" class="request-btn"> UPLOAD</button>
                    {% elif student.sanction == 'community_service' %}
                        <a class="request-btn" href="{% url 'studentLife_discipline:community-service-tracker' student.studentID %}">Community Service Tracker</a>
                    {% elif student.sanction == 'apology_letter_community_service' %}
                        {% if not student.apology_letter %}
                        <label for="apology_letter">Upload Apology Letter:</label>
                        <input type="file" name="apology_letter">
                        <br>
                        <br>
                        <button type="submit" class="request-btn"> UPLOAD</button>
                        {% else %}
                        <a class="request-btn" href="{% url 'studentLife_discipline:community-service-tracker' student.studentID %}">Community Service Tracker</a>
                        {% endif %}
                    {% endif %}
                </form>
                
            {% endif %}
            
        {% else %}
        <p>Reason: <u>{{existing_request.reason}}</u></p>
        {% if existing_request.is_approved %}
        <div class="req-btn">
            <a class="request-btn" href="{% url 'studentLife_discipline:GoodMoralTemplate' student.studentID %}">Print Good Moral</a>
        </div>
       
        {% elif existing_request.is_declined%}
        <a class="request-btn">Declined</a>
        {% else %}
        <div class="req-btn">
            <a class="request-btn">PENDING...</a>
        </div>
        {% endif %}
        {% endif %}
    </div>
</body>
</html>

base/templates/base/goodmoral_login.html
{% extends 'main.html' %}

{% load static %}
{% block bodycontent %}

<link rel="stylesheet" href="{% static 'studentdiscipline/css/Goodmoral.css' %}">
<script src="{% static 'studentdiscipline/js/date2.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<div class="request-container">
    <img src="{% static 'studentdiscipline/imgs/newlogo.jpg' %}">
    <div class="request-content">
        <div class="req-inputs">
            <form method="post" action="">
                {% csrf_token %}
                <div class="autodate-container">
                    <input type="datetime-local" name="autodate"  id="autodate" class="autodate">
                </div>
                <label for="student_id">Enter Student ID:</label>
                <input type="text" placeholder="Student ID" id="student_id" name="student_id" class="inputs">
                <button type="submit" class="myButton1" name="goodmoral">Enter</button>
            </form>
            {% if no_student_found %}
                <script>
                    document.addEventListener('DOMContentLoaded', function() {
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            text: 'No student found with that ID.',
                        });
                    });
                </script>
            {% endif %}
            
        </div>
    </div>
</div>

{% endblock %}