base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "studentLife_discipline"

urlpatterns = [
    #path('', views.caseProfile, name="case-profile"),
    path('newcase', views.NewCase, name="NewCase"),
    path('CaseList/', views.caseList, name="case-list"),
    #path('case-list/', views.caseList, name="case-list"),

    #COMMUNITY SERVICE
    path('community-service-tracker/<int:student_id>/', views.serviceTracker, name="community-service-tracker"),

    #GOOD MORAL URL
    path('RequestGoodMoral/', views.req_goodmoral, name="req_goodmoral"),
    path('goodmoral/<str:student_id>/', views.goodmoral_detail, name='goodmoral_detail'),
    path('GoodMoralTemplate/<str:student_id>/',views.GoodMoralTemplate, name="GoodMoralTemplate"),

    path('Transaction/', views.transaction, name='transaction'),
    path('approve/<int:pk>/', views.approve_request, name='approve_request'),
    path('decline/<int:pk>/', views.decline_request, name='decline_request'),

    #CRUD
    path('update-case/<str:pk>/', views.updateCase, name='update-case'),
    path('delete-case/<str:pk>/', views.deletecaserecord, name='deletecaserecord'),
    
    
    #modal part
    path('SavedSuccesfully/', views.savedcaseprofile, name="savedcaseprofile"),
     path('DeleteCaseRecord/<str:pk>/', views.deletecaserecord, name='deletecaserecord'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobplacement/urls.py
from django.urls import path
from .views import search_suggestions, company_suggestions
from . import views
from django.conf import settings
from django.conf.urls.static import static
from custom_user.views import index as cu_index
app_name='jobplacement'

urlpatterns = [
    path('jobplacement/', views.mainpage, name="home"),
    # OJT HIRING THINGS
    path('jobplacement/ojthiring/admin', views.ojt_hiring, name="ojt_hiring"),
    path('jobplacement/ojthiring/admin/assign', views.ojt_assign_student, name='ojthiring_assign'),
    path('jobplacement/ojthiring/more/<str:id>', views.ojt_hiring_info, name='ojthiring_info'),
    path('jobplacement/ojt/requirements/tracker/', views.ojtRequirements_tracker, name="ojt_requirements_tracker"),
    path('jobplacement/ojt/requirements/tracker/update', views.ojt_requirements_accept, name='ojt_requirement_update'),
    path('jobplacement/ojthiring/clear', views.del_ojt, name="del_ojt"),
    path('jobplacement/ojt_requirements/download', views.download_zipped_ojt_templates, name="ojt_requiremets_download"),
    path('jobplacement/ojt/requirements/submit', views.ojt_requirements_submit, name='ojt_requirements_submit'),
    path('jobplacement/ojthiring/delete/<int:id>', views.ojthiring_delete, name="ojt_hiring_delete"),
   
    #   Career Guidance THINGS
    path('jobeplacement/main/', views.seminar, name="seminar_page"),
    # path('jobplacement/new_seminar/', views.newSeminar, name="new_seminar"), # create new seminar
    path('jobplacement/seminar/attendance/manager/<int:id>', views.manage_attendance, name='manage_att'), # manage students with attendance
    path('jobplacement/pending_student_att', views.pend_attendance, name='pending_attendance'), # set attendance to pending
    path('jobplacement/attendance/cancel/<str:id>', views.cancel_pending, name="cancel_pending"), # cancel pending
    path('jobplacement/seminar/attendance/manager/jobplacement/attendance/attend_all/<str:id>', views.attend_all_pending),
    path('jobplacement/attendance/attend_all/<str:id>', views.attend_all_pending, name='attend_all_pending'),
    path('jobplacement/seminar/delete/<int:id>', views.seminar_delete, name='seminar_delete'),

    # Suggestions
    path('suggestions/', search_suggestions.as_view(), name='search_suggestions'),
    path('suggestions/companies', company_suggestions.as_view(), name='company_suggestions'),

    # Transaction Report
    path('jobplacement/report/', views.transRep, name="job_trans_rep"), # report page
    # path('jobplacement/report/creation', views.transaction_creation, name="new_transaction"),
    path('jobplacement/report/print', views.transRep_print, name="rep_print"), # print report

    # Non Academic Issuance
    path('jobplacement/non_acad', views.non_acad_page, name="non_acad"),
    
    # DELETABLE PATHS
    path('jobplacement/login/', cu_index, name="student_login"),
    # path('jobplacement/signup/', views.student_signup_view, name="student_signup"),
    path('jobplacement/login/admin/', views.admin_login, name="admin_login"),
    path('jobplacement/signup/admin', views.admin_signup_view, name="admin_signup"),
    path('jobplacement/logout', views.logout_user, name="logout_user"),

    # ---------------------- STUDENTS PATHS ----------------------------------
    # homescreen sa login og admin    
    path('jobplacement/homepage/admin_student', views.admin_student, name='admin_student'),

    path('jobplacement/ojt/requirements/tracker/view/iframe/<int:id>', views.view_pdf, name='view_pdf'),
    path('jobplacement/upload/', views.file_scrapper, name='scrapper'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentLife/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('custom_user.urls', 'custom_user'), namespace='custom_user')),
    path('', include(('studentLife_system.urls', 'studentLife_system'), namespace='studentLife_system')),
    path('', include('jobplacement.urls')),
    path('medical/', include(('medicalv2.urls'), namespace='medicalv2')),
    path('discipline/', include(('base.urls'), namespace='studentLife_discipline')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobplacement/models.py
import os
from django import forms
from django.db import models
from django.template.defaultfilters import truncatechars
from django.contrib.auth.models import User, AbstractBaseUser, PermissionsMixin
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import Permission, Group

from .managers import AdminUserManager, StudentUserManager
from studentLife_system.models import studentInfo as StudentUser
# Create your models here.
 
class JobPlacementAdminUser(AbstractBaseUser, PermissionsMixin):
    admin_id = models.AutoField(primary_key=True)
    email = models.EmailField(_("email address"), unique = True)
    firstname = models.CharField(max_length=50, blank=False, null=False, default="")
    lastname = models.CharField(max_length=50, blank=False, null=False, default="")
    middlename = models.CharField(max_length=50, null=True, blank=True, default="")
    is_staff = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
 
    objects = AdminUserManager()

    def __str__(self):
        return self.email
    
        #define reverse accessor for GROUP
    groups = models.ManyToManyField(
        Group,
        verbose_name=_("groups"),
        blank=True,
        related_name="admin_user_groups"  # Specify a related_name to resolve the clash
    )
        #define reverse accessor for Permission
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=_("user permissions"),
        blank=True,
        related_name="admin_user_permissions"  # Specify a related_name to resolve the clash
    )

# open ojt from companies
class OJTCompany(models.Model):
    DAY = "Day Shift"
    NIGHT = "Night Shift"

    shift_options = [
        (DAY, 'Day Shift'),
        (NIGHT, 'Night Shift'),
    ]

    company_id = models.AutoField(primary_key = True)   
    company_name = models.CharField(max_length=225, null=False, blank=False, default="")
    owner = models.CharField(max_length=100, null=False, blank=False, default="")
    position = models.CharField(max_length=100, null=False, blank=False, default="")
    address = models.CharField(max_length=100, null=False, blank=False, default="")
    description = models.TextField(null=False, blank=True)
    company_contact = models.CharField(max_length=50, null=True)
    number_of_slots = models.PositiveIntegerField(null=False, blank=False, default=1)
    shift = models.CharField(max_length=12, choices=shift_options, default=DAY)
    

    def __str__(self):
        return self.company_name
    
class OJTStudent(models.Model):
    ojt_id = models.AutoField(primary_key=True)
    studID = models.OneToOneField(StudentUser, on_delete=models.PROTECT, unique=True)
    company_id = models.ForeignKey(OJTCompany, on_delete=models.PROTECT)
    date_started = models.DateField(auto_now=True)
    duration = models.PositiveIntegerField(null=False, blank=False, default=100)
    def __str__(self):
        return f"{self.ojt_id}"
    
    class Meta:
        ordering = ['date_started']

class OJTRequirements(models.Model):
    PENDING = 'Pending'
    ACCEPTED = 'Accepted'
    DECLINED = 'Declined'
    NOFILE = 'No file'
    STATUS_CHOICES = [
            (PENDING, 'Pending'),
            (ACCEPTED, 'Accepted'),
            (DECLINED, 'Declined'),
            (NOFILE, 'No file')
    ]

    ojt_requirement_id = models.AutoField(primary_key=True)
    company_id = models.ForeignKey(OJTCompany, on_delete=models.CASCADE, null=True, blank=True, default="")
    student_id = models.ForeignKey(StudentUser, on_delete=models.CASCADE) # Change to Students Model
    non_disclosure = models.FileField(blank=True, upload_to='upload/ojt_requirements/')
    biodata = models.FileField(blank=True, upload_to='upload/ojt_requirements/')
    parents_consent = models.FileField(blank=True, upload_to='upload/ojt_requirements/')
    application_letter = models.FileField(blank=True, upload_to='upload/ojt_requirements/')
    medical = models.FileField(blank=True, upload_to='upload/ojt_requirements/')
    moa = models.FileField(blank=True, upload_to='upload/ojt_requirements/')
    endorsement = models.FileField(blank=True, upload_to='upload/ojt_requirements/')
    certification = models.FileField(blank=True, upload_to='upload/ojt_requirements/')

    nondis_stat = models.CharField(max_length = 20, choices = STATUS_CHOICES, default=NOFILE)
    biodata_stat = models.CharField(max_length = 20, choices = STATUS_CHOICES, default=NOFILE)
    consent_stat = models.CharField(max_length = 20, choices = STATUS_CHOICES, default=NOFILE)
    apl_letter_stat = models.CharField(max_length = 20, choices = STATUS_CHOICES, default=NOFILE)
    medical_stat = models.CharField(max_length = 20, choices = STATUS_CHOICES, default=NOFILE)
    moa_stat = models.CharField(max_length = 20, choices = STATUS_CHOICES, default=NOFILE)
    endorsement_stat = models.CharField(max_length = 20, choices = STATUS_CHOICES, default=NOFILE)
    cert_stat = models.CharField(max_length = 20, choices = STATUS_CHOICES, default=NOFILE)

    is_valid = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.non_disclosure and (self.nondis_stat == self.NOFILE or self.nondis_stat == self.DECLINED):
            self.nondis_stat = self.PENDING
        if self.biodata and (self.biodata_stat == self.NOFILE or self.biodata_stat == self.DECLINED):
            self.biodata_stat = self.PENDING
        if self.parents_consent and (self.consent_stat == self.NOFILE or self.consent_stat == self.DECLINED):
            self.consent_stat = self.PENDING
        if self.application_letter and (self.apl_letter_stat == self.NOFILE or self.apl_letter_stat == self.DECLINED):
            self.apl_letter_stat = self.PENDING
        if self.medical and (self.medical_stat == self.NOFILE or self.medical_stat == self.DECLINED):
            self.medical_stat = self.PENDING
        if self.moa and (self.moa_stat == self.NOFILE or self.moa_stat == self.DECLINED):
            self.moa_stat = self.PENDING
        if self.endorsement and (self.endorsement_stat == self.NOFILE or self.endorsement_stat == self.DECLINED):
            self.endorsement_stat = self.PENDING
        if self.certification and (self.cert_stat == self.NOFILE or self.cert_stat == self.DECLINED):
            self.cert_stat = self.PENDING
            
        super(OJTRequirements, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.student_id.email}"

class Seminar(models.Model):
    seminar_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, null=False, default="")
    theme = models.CharField(max_length=150, null=False, default="")
    date_of_event = models.DateField(null=False, default="")
    image = models.FileField(upload_to='upload/seminar_imgs', null=True, blank=True)  # Add this line   

    def __str__(self):
        return f"{self.seminar_id}"

class SeminarAttendance(models.Model):
    sem_at_id = models.AutoField(primary_key=True)
    student_id = models.ForeignKey(StudentUser, on_delete=models.CASCADE) # Change to studentModel
    seminar_id = models.ForeignKey(Seminar, null=True, on_delete=models.SET_NULL)
    attended = models.BooleanField(default=False)
    ispending = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.sem_at_id}, is attended {self.attended}"
    
class TransactionReport(models.Model):
    STUDENT = "Student"
    ADMIN = "Admin"
    user_type_choice = [
        (STUDENT, 'Student'),
        (ADMIN, 'Admin')
    ]
    # Modify the user field to allow both StudentUser and JobPlacementAdminUser instances
    report_id = models.AutoField(primary_key=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, default=1)
    object_id = models.CharField(max_length=30, null=False, blank=False, default="1")
    user = GenericForeignKey('content_type', 'object_id') 
    action = models.CharField(max_length=255, null=False, blank=False, default="None")
    date_created = models.DateTimeField(auto_now_add=True)
    user_type = models.CharField(max_length=50, choices=user_type_choice, default=STUDENT)


    class Meta:
        verbose_name = 'Transaction Report'
        verbose_name_plural = 'Transaction Reports'
        ordering = ['date_created']

    def __str__(self):
        return f"{self.user} - {self.action} at {self.date_created.strftime('%Y-%m-%d %H:%M:%S')}"

# class StudentUser(AbstractBaseUser, PermissionsMixin):
#     BSIT = "Bachelor of Science Information and Technology"
#     BEED = "Bachelor of Elementary Education"
#     BSED = "Bachelor of Secondary Education"
#     BIT_COMTECH = "Bachelor of Industrial Technology Major in Computech"
#     BIE = "Bachelor of Industrial Engineering"
#     FORESTRY = "Bachelor of Science and Forestry"
#     PSYCH = "Bachelor of Science"
#     BAEL = "Bachelor of English Literature"
#     CRIM = "Bachelor of Science Criminology"
#     HM = "Bachelor of Science Hospitality and Management"
#     TOURISM = "Bachelor of Science Hospitality and Tourism"
#     CAS = "Bachelor of Crafts Arts and Science"
#     ES = "Bachelor of Environmental Science"

#     program_choices = [
#             (BSIT, 'Bachelor of Science Information and Technology'),
#             (BEED, 'Bachelor of Elementary Education'),
#             (BSED, 'Bachelor of Secondary Education'),
#             (BIT_COMTECH, 'Bachelor of Industrial Technology Major in Computech'),
#             (BIE, 'Bachelor of Industrial Engineering'),
#             (FORESTRY, 'Bachelor of Science and Forestry'),
#             (PSYCH, 'Bachelor of Science'),
#             (BAEL, 'Bachelor of English Literature'),

jobplacement/templates/jobplacement/admin_login.html
{% extends 'index.html' %}

{% block headcontent %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'jobplacement/styles/admin_login.css' %}?1206">
{% endblock headcontent %}

{% block bodycontent %}

    <section>
    <!-- STUDENT LOGIN PAGE -->
        {% if page == 'admin_login' %}
            {% if form %}
            
            <form id="login_id" action="{% url 'jobplacement:admin_login' %}" method="POST" id="admin_signup_form">
                {% csrf_token %}
                {{ form.as_div}}
                <!-- <label for="">Email</label>
                <input type="email" name="{{ form.email.name }}">

                <label for="">Password</label>
                <input type="password" name="{{ form.password.name }}"> -->

                <input type="submit" value="Login">
            </form> 
            {% endif %}

            <a href="{% url 'jobplacement:admin_signup' %}">Admin Signup</a>
        {% else %}
            {% if form %}
            <form id="signup_form" action="{% url 'jobplacement:admin_signup' %}" method="POST" id='admin_signup_form'>
                {% csrf_token %}
                <div class="container">
                    <h1>Admin Signup</h1>
                    {{ form.as_div }}
                    <!-- <label for="email">Email:</label>
                    <input type="email" name="{{ form.email.name}}">

                    <label for="firstname">Firstname:</label>
                    <input type="text" name="{{ form.firstname.name}}">

                    <label for="lastname">Lastname:</label>
                    <input type="text" name="{{ form.lastname.name}}">

                    <label for="middlename">Middlename:</label>
                    <input type="text" name="{{ form.middlename.name}}">

                    <label for="studID">Student ID:</label>
                    <input type="text" name="{{ form.studID.name}}">

                    <label for="lrn">LRN:</label>
                    <input type="text" name="{{ form.lrn.name}}">

                    <label for="yearlvl">yearlvl:</label>
                    <input type="text" name="{{ form.yearlvl.name}}">

                    <label for="sex">Sex:</label>
                    <input type="text" name="{{ form.sex.name}}">

                    <label for="contact">Contact:</label>
                    <input type="text" name="{{ form.contact.name }}">

                    <label for="password1">Password:</label>
                    <input type="text" name="{{ form.password1.name}}">

                    <label for="password2">Confirm Password:</label>
                    <input type="text" name="{{ form.password2.name}}"> -->
                    <input type="submit" value="Sign up">
                </div>
            </form>
            {% endif %}
        {% endif %}
    </section>
{% endblock bodycontent %} 

jobplacement/templates/jobplacement/main.html
{% extends 'index.html' %}

{% block bodycontent %}

{% endblock bodycontent %}

jobplacement/templates/jobplacement/ojthiring.html
{% extends 'index.html' %}

{% block headcontent %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'jobplacement/styles/ojthiring.css' %}?249 ">

{% endblock headcontent %} 
    
{% block bodycontent %}
    
    <section>
        <div class="intro">
            <p>OJT Hiring</p>
        </div>
        <hr id="demo">
        <div id="desc">
            <p>Cebu Technological University - Argao Campus offers internship opportunities for students who may be interested in further developing their skills.</p>
            <p>Find internship opportunities below and get started: </p>
        </div>

        {% if request.user.is_staff %}

        <!-- Add company Form-->
        <!-- <div class="container">      -->
            <div class="button-container">
                <button class="showform2">Assign Student</button>
                <button class="showform">Add Company</button>
            </div>

                <div class="showform_container">
                    <div class="form_container">
                        <button class="closeform">×</button>
                        <form action="{% url 'jobplacement:ojt_hiring' %}" method="POST">
                            {% csrf_token %}
                            <div>
                                <!-- <label for="{{ form.student.name }}">Student ID:</label>
                                <input type="text" name="stud_id" id="stud_id">
                                <div class="search">
                                    <ul id="search_suggestions">
                                    </ul>
                                </div> -->
                                <label for="company">Company Name:</label>
                                <input type="text" name="{{ form.company_name.name }}">

                                <label for="address">Address:</label>
                                <input type="text" name="{{ form.address.name }}">

                                <label for="owner">Owner:</label>
                                <input type="text" name="{{ form.owner.name }}">
                                
                                <label for="position">Position:</label>
                                <input type="text" name="{{ form.position.name}}">

                                <label for="company_contact">Company Contact:</label>
                                <input type="text" name="{{ form.company_contact.name}}">
                                
                                <label for="Shift">Shift:</label>
                                {{ form.shift }}
                                
                                <label for="number_of_slots">Slots:</label>
                                <input type="number" name="{{ form.number_of_slots.name }}">
                
                                <label for="position">Description:</label>
                                <textarea type="text" name="{{ form.description.name }}" rows="4"></textarea>
                            </div>
                            <input type="submit" value="Submit">
                        </form>
                    </div>
                </div>
        <!-- </div> -->

        <!-- Assign student to company form-->
        <!-- <div class="container"> -->
            <div class="studentcontainer">
                <div class="studentshow">
                    <button class="closeform2">×</button>
                
                    <!-- STUDENT ASSIGNING FORM -->
                    <form action="{% url 'jobplacement:ojthiring_assign' %}" method="POST">
                        {% csrf_token %}
                        <label for="company">Company:</label>
                        <input id="company_id_holder" type="hidden" name="{{ assign_form.company_id.name}}" value="">
                        <input id="assign_company_id" type="text" name="company_holder">
                        <ul id="company_suggestions"></ul>
                
                        <label for="student">Student:</label>
                        <input id="student_id_holder" type="hidden" name="{{ assign_form.studID.name }}" value="">
                        <input id="assign_student_id" type="text" name="student_holder">
                        <ul id="assign_student_suggestions"></ul>

                        <label for="duration">Duration of OJT (hours):</label>
                        <input type="number" name="{{ assign_form.duration.name}}">
                
                        <label for="endorser">Endorser Fullname:</label>
                        <input type="text" name="endorser_name">
                
                        <label for="endorser_num">Endorser Phone:</label>
                        <input type="text" name="endorser_num">
                
                        <label for="endorser_email">Endorser Email:</label>
                        <input type="text" name="endorser_email">
                
                        <label for="endorser_program">Endorser Program:</label>
                        <select name="endorser_program" id="">
                            <option value="BSIT">BSIT</option>
                            <option value="BEED">BEED</option>
                            <option value="BSED">BSED</option>
                            <option value="BIT_COMTECH">BIT_COMTECH</option>
                            <option value="BIE">BIE</option>
                            <option value="FORESTRY">FORESTRY</option>
                            <option value="PSYCH">PSYCH</option>
                            <option value="BAEL">BAEL</option>
                            <option value="CRIM">CRIM</option>
                            <option value="HM">HM</option>
                            <option value="TOURISM">TOURISM</option>
                            <option value="CAS">CAS</option>
                            <option value="ES">ES</option>
                        </select>  
                
                        <input type="submit" value="Confirm">
                    </form>
                </div>
                
            </div>
        <!-- </div> -->
        {% endif %}

        <!-- Samples -->
        {% for hiring in ojt_list %}
        <div class="show_container">
            <div class="showbox">
                <button class="close-top">×</button>
                <h1>{{ hiring.company_name }}</h1>
                <div class="info-groups-container">
                    <div class="info-group">
                        <img src="{% static '/jobplacement/imgs/human.png' %}" alt="human">
                        <h3 style="font-weight: bold;">Employer:</h3> 
                        <h3 class="hiring">{{ hiring.owner }}</h3>
                    </div>
                    <div class="info-group">
                        <img src="{% static '/jobplacement/imgs/briefcase.png' %}" alt="case">
                        <h3 style="font-weight: bold;">Position:</h3> 
                        <h3 class="hiring">{{ hiring.position }}</h3>
                    </div>
                    <div class="info-group">
                        <img src="{% static '/jobplacement/imgs/placeholder.png' %}" alt="arrow">
                        <h3 style="font-weight: bold;">Address:</h3> 
                        <h3 class="hiring">{{ hiring.address }}</h3>
                    </div>
                    <div class="info-group">
                        <img src="{% static '/jobplacement/imgs/phone.png' %}" alt="phone">
                        <h3 style="font-weight: bold;">Contact:</h3> 
                        <h3 class="hiring">{{ hiring.company_contact }}</h3>
                    </div>
                    <div class="info-group">
                        <img src="{% static '/jobplacement/imgs/clock.png' %}" alt="clock">
                        <h3 style="font-weight: bold;">Work Shift:</h3> 
                        <h3>{{ hiring.shift }}</h3>
                    </div>
                    <div class="info-group">
                        <img src="{% static '/jobplacement/imgs/plus.png' %}" alt="plus">
                        <h3 style="font-weight: bold;">Slots Available:</h3> 
                        <h3>{{ hiring.number_of_slots }}</h3>
                    </div>
                </div>
                <h3>Job Description:</h3>
                <p>{{ hiring.description }}</p>
                <button class="close">Close</button>
            </div>
        </div>
        {% endfor %}

        {% for hiring in ojt_list %}
        <div class="card">
            <div class="card__content">
                {% if request.user.is_staff %}
                <form action="{% url 'jobplacement:ojt_hiring_delete' hiring.company_id %}" id="myForm">
                    {% csrf_token %}
                    <input type="submit" value="Delete">
                </form>
                {% endif %}
                <h1>{{ hiring.company_name }}</h1>
                <div class="info-group">
                    <h3>Employer:</h3> 
                    <h3 class="hiring">{{ hiring.owner }}</h3>
                </div>
                <div class="info-group">
                    <h3>Address:</h3> 
                    <h3 class="hiring">{{ hiring.address }}</h3>
                </div>
                <div class="info-group">
                    <h3>Contact Details:</h3> 
                    <h3 class="hiring">{{ hiring.company_contact }}</h3>
                </div>
                <ul>
                    <li>{{ hiring.description }}</li>
                </ul>
                <button class="btnshow">Read More</button>
                {% if request.user.is_staff %}
                    <a class="showtable" href="{% url 'jobplacement:ojthiring_info' hiring.company_id %}">View</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        
    <!-- </div> -->
    </section>
    <script src="{% static 'jobplacement/scripts/ojthiring_show.js' %}?321"></script>
{% endblock bodycontent %}

jobplacement/templates/jobplacement/seminar_page.html
{% extends 'index.html' %}

{% block headcontent %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'jobplacement/styles/seminarpage.css' %}?506">
{% endblock headcontent %}

{% block bodycontent %}
<section>
    <div class="intro">
        <p>Career Guidance Tracker</p>
    </div>
    <hr id="demo">
    
    {% for seminar in seminars %}
    <div class="container">
        <div class="card">
            {% if request.user.is_staff %}
                <form action="{% url 'jobplacement:seminar_delete' seminar.seminar_id %}" method='POST' id="myForm">
                    {% csrf_token %}
                    <input type="submit" value="Delete">
                </form>
            {% endif %}
            <div class="info-group">
                <h3>Title:</h3> 
                <a href="{% url 'jobplacement:manage_att' seminar.seminar_id %}">{{ seminar.title }}</a>
            </div>
            <div class="info-group">
                <h3>Theme:</h3> 
                <h3 class="hiring">{{ seminar.theme }}</h3>
            </div>
            <div class="info-group">
                <h3>Date of Event:</h3> 
                <h3 class="hiring">{{ seminar.date_of_event }}</h3>
            </div>
            {% if seminar.image %}
            <img src="{{ seminar.image.url }}" alt="{{ seminar.title }}">
            {% else %}
                <p>No image available</p>
            {% endif %}
        </div>
    </div>
    {% endfor %}

    {% if request.user.is_staff %}
        <div class="button-container">
            <button class="showform">Add Event</button>
        </div>
    {% endif %}
    <div class="showform_container">
        <div class="form_container">
            <button class="closeform">×</button>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <label for="{{ form.title.name }}">Title</label>
                <input type="text" name="{{ form.title.name }}">

                <label for="{{ form.title.name }}">Theme</label>
                <input type="text" name="{{ form.theme.name }}">

                <label for="date">Date of Event:</label>
                <input id="date_filter" type="date" name="{{ form.date_of_event.name }}">
                
                <label for="image">Upload Image</label>
                {{ form.image }}
                
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
</section>
<script src="{% static 'jobplacement/scripts/ojthiring_show.js' %}?320"></script>
{% endblock bodycontent %}