base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "studentLife_discipline"

urlpatterns = [
    #path('', views.caseProfile, name="case-profile"),
    path('newcase', views.NewCase, name="NewCase"),
    path('CaseList/', views.caseList, name="case-list"),
    #path('case-list/', views.caseList, name="case-list"),

    #COMMUNITY SERVICE
    path('community-service-tracker/<int:student_id>/', views.serviceTracker, name="community-service-tracker"),

    #GOOD MORAL URL
    path('RequestGoodMoral/', views.req_goodmoral, name="req_goodmoral"),
    path('goodmoral/<str:student_id>/', views.goodmoral_detail, name='goodmoral_detail'),
    path('GoodMoralTemplate/<str:student_id>/',views.GoodMoralTemplate, name="GoodMoralTemplate"),

    path('Transaction/', views.transaction, name='transaction'),
    path('approve/<int:pk>/', views.approve_request, name='approve_request'),
    path('decline/<int:pk>/', views.decline_request, name='decline_request'),

    #CRUD
    path('update-case/<str:pk>/', views.updateCase, name='update-case'),
    path('delete-case/<str:pk>/', views.deletecaserecord, name='deletecaserecord'),
    
    
    #modal part
    path('SavedSuccesfully/', views.savedcaseprofile, name="savedcaseprofile"),
     path('DeleteCaseRecord/<str:pk>/', views.deletecaserecord, name='deletecaserecord'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_user/urls.py
from django.urls import path
from . import views

app_name = 'custom_user'

urlpatterns = [
    path('index/', views.index, name='index'),  # Changed 'login/' to '' for the index page
    path('register/', views.register, name='register'),
    path('login_user/', views.login_user, name='login'),  # Changed 'login/' to 'login_user/'
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('login_admin/', views.login_admin, name='login_admin'),
    path('logout/', views.logout_user, name='logout'),
]

jobplacement/urls.py
from django.urls import path
from .views import search_suggestions, company_suggestions
from . import views
from django.conf import settings
from django.conf.urls.static import static
from custom_user.views import index as cu_index
app_name='jobplacement'

urlpatterns = [
    path('jobplacement/', views.mainpage, name="home"),
    # OJT HIRING THINGS
    path('jobplacement/ojthiring/admin', views.ojt_hiring, name="ojt_hiring"),
    path('jobplacement/ojthiring/admin/assign', views.ojt_assign_student, name='ojthiring_assign'),
    path('jobplacement/ojthiring/more/<str:id>', views.ojt_hiring_info, name='ojthiring_info'),
    path('jobplacement/ojt/requirements/tracker/', views.ojtRequirements_tracker, name="ojt_requirements_tracker"),
    path('jobplacement/ojt/requirements/tracker/update', views.ojt_requirements_accept, name='ojt_requirement_update'),
    path('jobplacement/ojthiring/clear', views.del_ojt, name="del_ojt"),
    path('jobplacement/ojt_requirements/download', views.download_zipped_ojt_templates, name="ojt_requiremets_download"),
    path('jobplacement/ojt/requirements/submit', views.ojt_requirements_submit, name='ojt_requirements_submit'),
    path('jobplacement/ojthiring/delete/<int:id>', views.ojthiring_delete, name="ojt_hiring_delete"),
   
    #   Career Guidance THINGS
    path('jobeplacement/main/', views.seminar, name="seminar_page"),
    # path('jobplacement/new_seminar/', views.newSeminar, name="new_seminar"), # create new seminar
    path('jobplacement/seminar/attendance/manager/<int:id>', views.manage_attendance, name='manage_att'), # manage students with attendance
    path('jobplacement/pending_student_att', views.pend_attendance, name='pending_attendance'), # set attendance to pending
    path('jobplacement/attendance/cancel/<str:id>', views.cancel_pending, name="cancel_pending"), # cancel pending
    path('jobplacement/seminar/attendance/manager/jobplacement/attendance/attend_all/<str:id>', views.attend_all_pending),
    path('jobplacement/attendance/attend_all/<str:id>', views.attend_all_pending, name='attend_all_pending'),
    path('jobplacement/seminar/delete/<int:id>', views.seminar_delete, name='seminar_delete'),

    # Suggestions
    path('suggestions/', search_suggestions.as_view(), name='search_suggestions'),
    path('suggestions/companies', company_suggestions.as_view(), name='company_suggestions'),

    # Transaction Report
    path('jobplacement/report/', views.transRep, name="job_trans_rep"), # report page
    # path('jobplacement/report/creation', views.transaction_creation, name="new_transaction"),
    path('jobplacement/report/print', views.transRep_print, name="rep_print"), # print report

    # Non Academic Issuance
    path('jobplacement/non_acad', views.non_acad_page, name="non_acad"),
    
    # DELETABLE PATHS
    path('jobplacement/login/', cu_index, name="student_login"),
    # path('jobplacement/signup/', views.student_signup_view, name="student_signup"),
    path('jobplacement/login/admin/', views.admin_login, name="admin_login"),
    path('jobplacement/signup/admin', views.admin_signup_view, name="admin_signup"),
    path('jobplacement/logout', views.logout_user, name="logout_user"),

    # ---------------------- STUDENTS PATHS ----------------------------------
    # homescreen sa login og admin    
    path('jobplacement/homepage/admin_student', views.admin_student, name='admin_student'),

    path('jobplacement/ojt/requirements/tracker/view/iframe/<int:id>', views.view_pdf, name='view_pdf'),
    path('jobplacement/upload/', views.file_scrapper, name='scrapper'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicalv2/urls.py
from django.urls import path
from . import views

app_name = 'medical'

urlpatterns = [
    path('patientbasicinfo/<int:student_id>/', views.patient_basic_info, name='patient_basicinfo'),
    path('medicalclearance/<int:student_id>/', views.medicalclearance_view, name='medicalclearance'),
    path('eligibilityform/<int:student_id>/', views.eligibilty_form, name='eligibility_form'),
    path('medicalcertificate/<int:student_id>/', views.med_cert, name='med_cert_for_intrams'),
    path('viewrequest/', views.view_request, name='viewrequest'),
    path('student/request/', views.submit_request, name="request"),
    path('patient/profile/', views.patient_profile, name='patient_profile'),
    path('physicalexam/<int:student_id>/', views.physical_examination, name='physical_exam'),
    path('medicalrequirementstracker/', views.student_medical_requirements_tracker, name='medtracker'),
    path('uploadrequirements/', views.upload_requirements, name='upload_requirements'),
    path('dentalservices/', views.dental_services, name='dentalservice'),
    path('dentalrequest/', views.dental_request, name='dentalrequest'),
    path('dentalschedule/', views.dental_schedule, name='dentalschedule'),
    path('listofpwd/', views.pwd_list, name='pwdlist'),
    path('pwd/<int:student_id>/', views.pwd_detail, name='pwd_detail'),
    path('prescriptions/', views.prescription, name='prescription'),
    path('prescriptionrecords/', views.view_prescription_records, name='prescription_records'),
    path('getstudentname/', views.get_student_name, name='get_student_name'),
    path('emergencyassistance/', views.emergency_asst, name='emergency_asst'),
    path('emergencyassistancerecords', views.view_emergency_health_records, name='emergency_health_records'),
    path('insuranceeligibility/', views.check_insurance_availability, name='insurance_eligibility'),
    # URL for the main transactions view
    path('transactions/', views.transactions_view, name='transactions'),
    path('monthly_transactions/', views.monthly_transactions_view, name='monthly_transactions'),
    path('daily_transactions/', views.daily_transactions_view, name='daily_transactions'),
    # path('yearly/', views.yearly_transactions, name='yearly_transactions'),
    # path('upload/', views.upload_file, name='upload'),
]

studentLife/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('custom_user.urls', 'custom_user'), namespace='custom_user')),
    path('', include(('studentLife_system.urls', 'studentLife_system'), namespace='studentLife_system')),
    path('', include('jobplacement.urls')),
    path('medical/', include(('medicalv2.urls'), namespace='medicalv2')),
    path('discipline/', include(('base.urls'), namespace='studentLife_discipline')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/studentorg/Main/Logins.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Logins</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/org.css' %}">
    <link rel="stylesheet" href="{% static '/css/general.css' %}">
    <link rel="stylesheet" href="{% static '/css/logins.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<style>
    a{
text-align: center;
    }
</style>
<body>
    <div class="logincontainer">
        <div class="maincontain">
            <div class="subcontain" style="height: 10%; align-items: stretch;
            flex-direction: column;">
                <h1 class="hd" style="display:flex; justify-content: center;">Logins</h1>
                    <a href="/admin_login" class="button" style="margin-top:20px;">Admin Login</a>
                    <a href="/officer_login" class="button">Officer Login</a>
                    <a href="/register_officer" class="button">Register Officer</a>
                    <a href="/Gen_Home" class="button"> Student View</a>
            </div>
        </div>
    </div>
</body>

</html>

templates/studentorg/Main/OrgMain.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Student Organization</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/org.css' %}">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<style>
.pages a,
.pages {
    color: black;
    transition: color 0.3s, transform 0.3s;
    text-decoration: none;
}

.pages a:hover{
    color: #FF8000;
    transform: scale(1.1);
}

.pf2 {
	list-style-type: none;
	border-bottom: 2px solid #FF8000;
	padding-bottom: 10px;
}
</style>

</head>
<body>
    <div class="nav-container">
        <div class="orange-bar">
            <img src="{% static '/css/CTU_logo.png' %}" class="logo">
            <img src="{% static '/css/barSort.png' %}" class="bars">
        </div>

        <nav class="side-nav">
            <ul>
                                <li><a href="#" class="studentlife-btn">OFFICE OF STUDENT LIFE
                        <span class="fas fa-caret-down first"></span>
                    </a>
                    <ul class="studentlife">
                        <li><a href="/equipmenttracker">Equipment Tracker</a></li>
                        <li><a href="/requestgmc">Good Moral Certificate Issuance</a></li>
                        <li><a href="/monthlyCalendar">Monthly Calendar of Activites</a></li>
                    </ul>
                </li>
                <li><a href="#" class="scholar-btn">SCHOLARSHIP
                        <span class="fas fa-caret-down second"></span>
                    </a>
                    <ul class="scholar-show">
                        <li><a href="#">Submission of Requirements Tracker</a></li>
                        <li><a href="#">Scholars Profile and Validation</a></li>
                        <li><a href="#">Grade Submission with GPA Computation</a></li>
                        <li><a href="#">Mentorship Program</a></li>
                        <li><a href="#">Admin Cost Liquidation Tracker</a></li>
                        <li><a href="#">CHED Reports Submission</a></li>
                        <li><a href="#">Transaction Reports</a></li>
                    </ul>
                </li>
                <li><a href="#" class="jobplace-btn">JOB PLACEMENT
                        <span class="fas fa-caret-down third"></span>
                    </a>
                    <ul class="jobplace-show">
                        <li><a href="{% url 'jobplacement:ojt_hiring' %}">OJT Hiring</a></li>
                            <li><a href="{% url 'jobplacement:seminar_page' %}">Career Guidance Tracker</a></li>
                            <li><a href="{% url 'jobplacement:ojt_requirements_tracker' %}">OJT Requirements Tracker</a></li>
                            {% if request.user.is_staff %}
                            <li><a href="{% url 'jobplacement:non_acad' %}">Non-Academic Award Issuance</a></li>
                            <li><a href="{% url 'jobplacement:job_trans_rep' %}">Transaction Reports</a></li>
                            {% endif%}
                            {% if request.user.is_superuser %}
                            <li><a href="{% url 'jobplacement:admin_signup' %}">Admin Signup</a></li>
                            {% endif %}
                            {% if request.user.is_staff %}
                            <li><a href="{% url 'custom_user:register' %}">Student Signup</a></li>
                            {% endif %} 
                    </ul>
                </li>
                <li><a href="#" class="student_disc-btn">STUDENT DISCIPLINE
                        <span class="fas fa-caret-down fourth"></span>
                    </a>
                    <ul class="student_disc-show">
                        <li><a href="{% url 'studentLife_discipline:NewCase' %}">Case Profile</a></li>
                        <li><a href="{% url 'studentLife_discipline:case-list' %}">Hours Rendered for Community Service Tracker</a></li>
                        <li><a href="{% url 'studentLife_discipline:req_goodmoral' %}">Good Moral Certificate Issuance</a></li>
                    </ul>
                </li>
                <li><a href="#" class="guide-btn">GUIDANCE
                        <span class="fas fa-caret-down fifth"></span>
                    </a>
                    <ul class="guide-show">
                        <li><a href="{% url 'studentLife_system:Individual Profile'%}">Individual Profile with Guidance
                                Concern</a></li>
                        <li><a href="{% url 'studentLife_system:Counseling App With Scheduler'%}">Counseling App with
                                Scheduler</a></li>
                        <li><a href="{% url 'studentLife_system:Exit Interview'%}">Exit Interview</a></li>
                        <li><a href="{% url 'studentLife_system:OJT Assessment'%}">OJT Assessments/Psychological
                                Issuance</a></li>

                    </ul>
                </li>
                <li><a href="#" class="alumni-btn">ALUMNI
                        <span class="fas fa-caret-down sixth"></span>
                    </a>
                    <ul class="alumni-show">
                        <li><a href="{% url 'studentLife_system:idRequest' %}">Alumni ID Requests</a></li>
                        <li><a href="{% url 'studentLife_system:graduateTracer' %}">Graduate Tracer</a></li>
                        <li><a href="{% url 'studentLife_system:alumni_events' %}">Alumni Reunion and Events</a></li>
                        <li><a href="{% url 'studentLife_system:jobfairs' %}">Job Fairs</a></li>
                        <li><a href="{% url 'studentLife_system:yearbook' %}">Digital Yearbook</a></li>

                    </ul>
                </li>
                <li><a href="#" class="community-btn">COMMUNITY INVOLVEMENT
                    <span class="fas fa-caret-down seventh"></span>
                </a>
                <ul class="community-show">
                    <li><a href="{% url 'studentLife_system:programs' %}">Events</a></li>
                    <li><a href="{% url 'studentLife_system:projects' %}">CrowdFunding Projects</a></li>
                </ul>
                </li>
                <li><a href="#" class="student_org-btn">STUDENT ORGANIZATION
                        <span class="fas fa-caret-down eight"></span>
                    </a>
                    <ul class="student_org-show">
                        <li><a href="{% url 'studentLife_system:Gen_Home' %}">Org Profile</a></li>
                    </ul>
                </li>
                <li><a href="#" class="medical-btn">MEDICAL
                        <span class="fas fa-caret-down ninth"></span>
                    </a>
                    <ul class="medical-show">
                        <li><a href="{% url 'medicalv2:upload_requirements' %}">Student Medical Requirements Tracker</a>
                        </li>
                        <li><a href="{% url 'medicalv2:request' %}">Medical Form Request</a></li>
                        <li><a href="{% url 'medicalv2:dentalservice' %}">Dental Services</a></li>
                        <br><br><br>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>

 

    <div class="container">
        <div class="headert" style="margin-left: 100px; margin-top: 100px; text-align:center; justify-content:center">
            <h1 class="pf2" style="color:black;">CTU-AC STUDENT ORGS</h1>
            <p class="pages" style="font-size:20px; color: black; padding-top:10px;">Quick Actions</p>
            <p class="pages pf2"><a href="{% url 'FSTLP_profile' %}">FSTLP</a> - <a href="{% url 'SI_profile' %}">SI++</a> - <a href="{% url 'THEEQUATIONERS_profile' %}">Equationers</a> - <a href="{% url 'SSG_profile' %}">SSG</a> - <a href="{% url 'TECHNOCRATS_profile' %}">Technocrats</a></p>
        </div>


        <div class="row">
            <a href="/FSTLP_profile" class="image"><img src="{% static '/css/org1.png' %}"></a>
            <a href="/SI_profile" class="image"><img src="{% static '/css/org2.png' %}"></a>
            <a href="/THEEQUATIONERS_profile" class="image"><img src="{% static '/css/org3.png' %}"></a>
        </div>
        <div class="row">
            <a href="SSG_profile" class="image"><img src="{% static '/css/org4.png' %}"></a>
            <a href="TECHNOCRATS_profile" class="image"><img src="{% static '/css/org5.png' %}"></a>
        </div>
    </div>
   
    <script src="{% static '/css/main.js' %}"></script>
</body>

</html>